### PR TITLE
Footer design

### PR DESCRIPTION
**Pull request by joshturner**
Footer css and html

### CODE REVIEW

**Comment by jungshadow** [comment]
👍 Looks like a good start, @joshturner!

I noticed we have an empty `footer` element in the main `div`. Worth removing? If you're not planning to use/style it, I can remove it in another PR, since it's in the React code.

**Comment by joshturner** [comment]
@jungshadow oh shoot. I thought I removed that. If you want to nab it in the dev branch that would be great. Thanks!

**Comment by joshturner** [comment]
@jungshadow since I am awful at git could you nab that modern.css and just discard the changes as it's the compiled css file? Sorry about that. I tried to stash it and discard the changes an wasn't able to resolve for the PR for some reason

**Comment by jungshadow** [comment]
@joshturner It's ok that the compiled files are in here. We actually need/want them. When we update gh-pages to launch the site, I'm going to do a straight rebase on the master branch. I merged the new develop branch changes for you though, so you'll need to another pull before you keep going: `$ git pull origin footer-design`

**Comment by joshturner** [comment]
@jungshadow this should be good to go.

**Comment by jungshadow** [comment]
LGTM

**Pull request merged**
