### PR TITLE
Updates styling and markup on error message to use .userContent module

### PR DESCRIPTION
**Pull request by jhjdesigns**

### CODE REVIEW

**Comment by jungshadow** [comment]
@jhjdesigns I checked out the changes here. Looks like the URLs are still dark on the red background. What changed besides the class names? Should I be doing something else in the generated HTML?

**Comment by jungshadow** [comment]
@jhjdesigns Should I merge as a bugfix (the HTML is better) and push the styles to another PR?

**Comment by jajohnso** [comment]
I'll look into this, not sure why you're seeing something different. In the words of Jason Sanville, "Looked good from my house."

**Comment by jungshadow** [comment]
@jhjdesigns You gotta get your GH accounts in order ;)

**Comment by jungshadow** [comment]
@jhjdesigns Did you ever have a chance to check this out?

**Pull request merged**
