### PR TITLE
Feature/issue 30 error messages

### LINKED ISSUE #30: Add Additional Error Messages for Various States
In situations where we don't have any polling locations or ballot information, we'll need error messages for:

- [x] When there's S/LEO information
- [x] When there isn't S/LEO information

If we can direct someone to a local election official to resolve issues, all the better.

### PR DESCRIPTION
**Pull request by jungshadow**
Fixes #30

### CODE REVIEW

**Comment by jungshadow** [comment]
There's clearly more work to do to improve the error messages, but it's a start.

@jhjdesigns Can you take a quick peep at this and give me a 👍 if it'll work?
@joshturner or @jhjdesigns: Do either one of you have the bandwidth to update the styles for the error box to account for more text and links? Currently, the links are a bit dark (see image below). I'd do it, but I'd like to get a handle on the arrangement/mental-model of the SCSS before I start hacking on it.

screenshot 2016-06-27 13 36 14

**Comment by jhjdesigns** [comment]
I probably won’t get a chance to work on this all week. Just got news that my grandfather passed away, so I’ll have to travel home for the services. I can hop on it after i’m back.

**Comment by jungshadow** [comment]
@joshturner - Since @jhjdesigns is out of commission for a few, do you have the bandwidth to tweak the styles a bit? If it's easy, feel free to commit changes to this PR. If it's easier/simpler, I can merge this into the develop branch and you edit there.

**Comment by joshturner** [comment]
Can yo merge and I can make a fresh branch from dev? Thanks!

**Comment by jungshadow** [comment]
@joshturner - Merged! Thanks!

**Pull request merged**
